### PR TITLE
Add note for using older MiHome mod as latest does not write pairings…

### PR DESCRIPTION
**Pull request by jeremysherriff**
….txt

### CODE REVIEW

**Comment by Ernst79** [comment]
@jeremysherriff Thanks for your input. However, I used the latest version yesterday (6.0.214), and it writes pairings.txt just fine. However, I saw that someone mentioned that you had to make the `logs` folder yourself beforehand. But that's written in the instructions. Perhaps something like that went wrong. Perhaps, you could try it again.

**Comment by jeremysherriff** [comment]
@Ernst79 yes I created the `logs` subdirectory first, the app the correctly created a structure under that (devices, misc etc) when I paired my first device. However no files (literally, no log files of any sort) were created when pairing the devices.

I removed that version and tried with an early 5.6.x and this time files were created, and so I attempted a couple of other versions assuming that the 6.x series was no longer able to achieve what we were needing.

I'll try with a modded v6 again and report findings.

**Comment by Ernst79** [comment]
Thats strange, I had no issue at all yesterday. Let me know, otherwise, I will add a note in the FAQ.

**Comment by jeremysherriff** [comment]
@Ernst79 ok I have tested, and it works fine.  The only difference I can think of is that this time I used a modern Android device (Samsung Galaxy S9+ phone, Android 10) whereas I originally tried on an old device (so that I did not disrupt my "main" Mi Home app) that is running Android 7.0 Nougat, and probably does not have the required Android API version to support the app. Normally the Play Store would ensure compatibility but side-loading the APK would have allowed me to bypass that, and as the app didn't actually crash I assumed it was working OK.

I will close this PR as unnecessary, but perhaps a note in the faq regarding a decent version of Android is appropriate as I can imagine that others will also use old or spare devices to avoid "disruption" of their primary Mi Home system by using a modded APK.  I can confirm that Android 7 and APK version 5.8 and 5.9 appear to work fine, it's just v6.x of the APK that doesn't work with the old device.

**Comment by Ernst79** [comment]
Thanks. I also used an old android 6, and it worked fine with 6.0.214. But I will add a note.

**Comment by jeremysherriff** [comment]
OK, that was a guess. Maybe it's to do with it being a tablet instead of a phone?  Whatever the reason, I've confirmed v6.x doesn't create the files on that device, but it looks like any recent version of v5.x does.  All versions work fine on my phone.

**Comment by Ernst79** [comment]
I've added a note to the FAQ, to try an old version, if pairings.txt isn't created.

**Pull request closed without merging**
