### PR TITLE
Binary sensors

### LINKED ISSUE #166: Use binary sensors
**Problem description**
Follow up of discussion in #159

MCCQ02HL and WX08ZM sensors are currently discovered as `sensors` with on/off state. However, these sensors are actually `binary_sensors`, not `sensors`. This causes that the sensors are only able to show `on/off` and not e.g. `closed/open`. 

**(Possible) Solution**
This issue is to discuss how to solve this. The final goal should be that binary sensors are discovered with the proper device class, and show their appropriate state. 

Proposal for device classes
MCCQ02HL --> `open/close` (DEVICE_CLASS: opening)
MCCQ02HL --> `light/dark` (DEVICE_CLASS: light)
WX08ZM  --> `power detected/no power` (DEVICE_CLASS: power)

**To Do**

To achieve this, we should 

- [x] move the monitoring to `__init__.py` (integration level)
- [x] keep the add_enties in `sensor.py` and `binary_sensor.py` at platform level)
- [x] move BLE ADV parser to HCIdump thread because this is the only way we can sort messages (see next task)
- [x] split the incoming messages into two separate queues (one for each platform)?
- [x] move the `SwitchingSensors` to `binary_sensor.py`

**Findings of other examples that could help**
I think the [smarty](https://github.com/home-assistant/core/tree/dev/homeassistant/components/smarty) can be used as an base example, although it has part of the code in a pypi package (pysmarty). 

What I found in the smarty component, is that there are two links between `__init__.py` and e.g. `sensor.py`
Data
- in `__init__.py`, data is collected in `smarty` and this is passed to `hass.data[DOMAIN]`
```
    smarty = Smarty(host=host)
    hass.data[DOMAIN] = {"api": smarty, "name": name}
```
- in `sensor.py` it gets the data via `smarty = hass.data[DOMAIN]["api"]`

Updating
- It uses `dispatcher_send(hass, SIGNAL_UPDATE_SMARTY)` in `__init__.py` after receiving data 
- In `sensor.py` it uses this in the entity. 

```
    async def async_added_to_hass(self):
        """Call to update."""
        async_dispatcher_connect(self.hass, SIGNAL_UPDATE_SMARTY, self._update_callback)

    @callback
    def _update_callback(self):
        """Call update method."""
        self.async_schedule_update_ha_state(True)
```

Not entirely sure how this update link exactly works.

### PR DESCRIPTION
**Pull request by Magalex2x14**
closes #166

### CODE REVIEW

**Comment by Magalex2x14** [comment]
I think we can do a public beta.

**Comment by Magalex2x14** [comment]
I checked the operation of binary sensors. And processing the battery data in binary_sensors (I didn't have to wait 24 hours, MCCGQ02HL sends all the data if the battery is removed and inserted back).

**Comment by Ernst79** [comment]
It works fine here, so OK to me to make a beta release

**Review by Ernst79 — APPROVED** [review]

**Comment by Magalex2x14** [comment]
Added some fixes. There are important ones among them, so also updated 0.8.4-beta tag.

**Comment by Ernst79** [comment]
Can I merge your changes in config_flow?

**Comment by Magalex2x14** [comment]
Yes, sure.

**Comment by Ernst79** [comment]
Just to make sure we don't get too far behind

**Comment by Magalex2x14** [comment]
I deliberately tackled small things that require long debugging and do not change the code much.

**Comment by Ernst79** [comment]
Sorry, seems I've done something wrong

image

I merged your changes, but it also deleted the binary_sensor branch. Oops

**Comment by Magalex2x14** [comment]
now I'll try to restore

**Comment by Ernst79** [comment]
I compared the two branches and created a PR to merge, but seems that is not the way to do this?

**Comment by Magalex2x14** [comment]
There seems to be a checkmark somewhere, whether to delete the original branch after merging

**Comment by Ernst79** [comment]
Ok, thanks. Learned something again. It is back online.

**Comment by Ernst79** [comment]
Can we merge this and release this as final, or are you still working on this one?

**Comment by Magalex2x14** [comment]
No, no, this work is over. We can release it, yes. The only thing is that there is ambiguity with the kettle, but I think we can leave it as it is.

**Comment by Ernst79** [comment]
Ok, I will make a release.

**Comment by Magalex2x14** [comment]
Thank you

**Pull request merged**
