### PR TITLE
add xiaomi lock E

### PR DESCRIPTION
**Pull request by huexpub**

### CODE REVIEW

**Comment by Ernst79** [comment]
Thanks, did you check wether the lock also sends the armed away ble data? You can check by adding "armed away" as binary sensor, like for the ZLMS17LM

**Comment by huexpub** [comment]
emm, add "armed away" not effect ,butit should have this function, I will analyze later few days

**Comment by Ernst79** [comment]
Did you analyse it?

**Comment by Ernst79** [comment]
Are you sure about the model name. According to here, it is XMZNMS04LM. This number looks more in line with the others.

**Pull request merged**
