### PR TITLE
Added passing the gateway ID

### PR DESCRIPTION
**Pull request by dmamontov**
Added passing the gateway ID to determine exactly which gateway caught the device, particularly useful for identifying people in the room. 

#### Example for myhomeiot/esphhome-components:
**esphome**
```yaml
.....

external_components:
  - source: github://myhomeiot/esphome-components
  - source: github://pr#2854
    components: [esp32_ble_tracker]

esp32_ble_tracker:

ble_gateway:
  devices:
    - mac_address: ...
  on_ble_advertise:
    then:
      homeassistant.event:
        event: esphome.on_ble_advertise
        data:
          packet: !lambda return packet;
          gateway_id: gateway_hall_1
```

**hass**
```yaml
- alias: ESPHome BLE Advertise
  mode: queued
  trigger:
    - platform: event
      event_type: esphome.on_ble_advertise
  action:
    - service: ble_monitor.parse_data
      data:
        packet: "{{ trigger.event.data.packet }}"
        gateway_id: "{{ trigger.event.data.gateway_id }}"
```

### CODE REVIEW

**Review by Ernst79 — APPROVED** [review]

**Review by Ernst79 — CHANGES_REQUESTED** [review]
I get one error is the HASSFEST test

```
Integrations: 1
Invalid integrations: 1

Integration ble_monitor - custom_components/ble_monitor:
Error: R] [SERVICES] Invalid services.yaml: required key not provided @ data['parse_data']['fields']['gateway_id']['description']. Got None

Error: Process completed with exit code 1.
```

**Comment by dmamontov** [comment]
> I get one error is the HASSFEST test
> 
> ```
> Integrations: 1
> Invalid integrations: 1
> 
> Integration ble_monitor - custom_components/ble_monitor:
> Error: R] [SERVICES] Invalid services.yaml: required key not provided @ data['parse_data']['fields']['gateway_id']['description']. Got None
> 
> Error: Process completed with exit code 1.
> ```

Added description

**Comment by Ernst79** [comment]
That was fast, looks good BTW. Thanks. Does this need some explanation in the documentation?

**Review by Ernst79 — APPROVED** [review]

**Comment by dmamontov** [comment]
> That was fast, looks good BTW. Thanks. Does this need some explanation in the documentation?

Just in case, I updated the documentation and added an example.

**Comment by Ernst79** [comment]
Thanks!

**Pull request merged**
