### PR TITLE
Restructuring of configuration parameters

### PR DESCRIPTION
**Pull request by Ernst79**
This PR aims to change the configuration parameters, as described in #141. 

This final format will be similar to this. This means that this is a breaking change 

```
sensor:
  - platform: mitemp_bt
     discovery: False
     devices:
     - mac: 'A4:C1:38:2F:86:6C'
       encryption_key: '217C568CF5D22808DA20181502D84C1B'
       name: Livingroom
     - mac: C4:7C:8D:6B:4F:F3
       encryption_key: 217C568CF5D22808DA20181502D84C1B
       temperature_unit: F
     - mac: 'B4:7C:8D:6B:4F:D3'
       temperature_unit: 'F'
```

Todo-list
- [x] Add new configuration parameters
- [x] Move `sensor_fahrenheit `to sensor --> `mac` and `temperature_unit`
- [x] Move `sensor_names `to sensor --> `mac` and `name`
- [x] Move `whitelist `to use sensor --> `mac` and `discovery`
- [x] Move `encryptors `to sensor --> `mac` and `encryption_key`
- [x] Remove old parameters
- [x] Code cleaning
- [x] Rewrite readme
- [x] Add faq how to convert configuration. 

Later, additional parameters can be added to sensor level, like `median `and `mean`.

### CODE REVIEW

**Comment by Ernst79** [comment]
@Magalex2x14 I think it is finished. Could you do a extensive review? The only thing I couldn't test is the `encryption_key` option, as I don't have such a device. I don't expect any problems with it, as I get the same aeskeys dictionary as before. I wrote some instructions on a separate page to convert old config to new config.

One question, it is not needed anymore to use these ` in front and after strings, like the MAC address. So we could update the instructions and remove them, e.g. around the MAC address. See the example above, where I show the difference between the first and second sensor. Both will work. Which is best to put in the instructions?

**Comment by Magalex2x14** [comment]
Awesome! I'll be ready to watch attentively tomorrow evening.
And about the ('), I myself was at a loss... If we are confident that they are in any case redundant, then it is better without them, I think... I propose to see how others have done :)

**Comment by Ernst79** [comment]
Yes, sure, I will have a look in other components. It's not that important, both work fine. 

Take your time. I propose that after your review, we will do a beta version first for a couple of days.

**Comment by Ernst79** [comment]
Have you tested this change with multiple sensors? I did something similar like you do now in my first attempt, but for some reason it only looked at the first MAC address and then quitte with an empty response. But I might have done something wrong in my first attempt. Your code looks cleaner. But we have to test this with multiple sensors.

**Review by Magalex2x14 — COMMENTED** [review]
Code:

I made some changes - removed unnecessary statements. The code works for me, I don't see any problems. My config:

```yaml
  - platform: mitemp_bt
    rounding: False
    decimals: 2
    period: 60
    log_spikes: True
    use_median: False
    batt_entities: True
    hci_interface:
      - 0
      - 1
      - 2
    report_unknown: True
    devices:
      - mac: '58:2d:34:31:40:00'
        name: sensor
      - mac: "A4:C1:38:2F:87:6B"
        encryption_key: "217C568CF5D22808D120181502D84C1B"
      - mac: "A4:C1:38:D1:6A:8D"
        encryption_key: "C99D2313182473B38A01086FEBF781BD"
    discovery: True
```

Instructions.
I had one question. It is not clear to me why such indentations work:

```yaml
     devices:
     - mac: 'A4:C1:38:2F:86:6C'
       name: Livingroom
       encryption_key: '217C568CF5D22808DA20181502D84C1B'
       temperature_unit: C
     - mac: 'C4:3C:4D:6B:4F:F3'
       name: Bedroom
       temperature_unit: F
     - mac: 'B4:7C:8D:6D:4C:D3'
```

Personally, it seems to me that such indentation can lead to potential problems. But this is just a feeling that I can’t support with anything yet.
In any case, I propose to bring it to this form (make it more distinct):

```yaml
     devices:
       - mac: 'A4:C1:38:2F:86:6C'
         name: Livingroom
         encryption_key: '217C568CF5D22808DA20181502D84C1B'
         temperature_unit: C
       - mac: 'C4:3C:4D:6B:4F:F3'
         name: Bedroom
         temperature_unit: F
       - mac: 'B4:7C:8D:6D:4C:D3'
```

What do you think?

**Comment by Magalex2x14** [comment]
> But we have to test this with multiple sensors.

Yes, I have several sensors, and everything is fine, I see corresponding messages in the debug log.

**Comment by Ernst79** [comment]
> What do you think?

Yes, that’s better. Both work nevertheless, but your indentation is how it should be. Will change that.

What do you want with the ‘ quotemarks? I can’t really find any logic in other integrations?

**Comment by Magalex2x14** [comment]
The only remark (I don't know if it's worth mentioning this in the instructions, it's obvious):
so far I have used a single secret for specifying encryption keys:

```yaml
lywsd03:
    "A4:C1:38:2F:87:6B": "217C568CF5D22808D120181502D84C1B"
    "A4:C1:38:D1:6A:8D": "C99D2313182473B38A01086FEBF781BD"
```
Now I have to break it and specify a separate secret for each sensor.

**Comment by Magalex2x14** [comment]
> What do you want with the ‘ quotemarks? I can’t really find any logic in other integrations?
It seems to me that it is better to have them, since they are safer with them (it is not known what the user will want to poke into the sensor name, for example, and how the validator might react to this), and syntax highlighting highlights these strings)

**Comment by Ernst79** [comment]
OK, that makes sense.

**Review by Magalex2x14 — APPROVED** [review]

**Comment by Ernst79** [comment]
> The only remark (I don't know if it's worth mentioning this in the instructions, it's obvious):
> so far I have used a single secret for specifying encryption keys:
> 
> ```yaml
> lywsd03:
>     "A4:C1:38:2F:87:6B": "217C568CF5D22808D120181502D84C1B"
>     "A4:C1:38:D1:6A:8D": "C99D2313182473B38A01086FEBF781BD"
> ```
> 
> Now I have to break it and specify a separate secret for each sensor.

I don’t understand what you are saying. What do you mean by ‘a single secret’?

**Comment by Magalex2x14** [comment]
Before that, it was enough:
```yaml
encryptors: !secret lywsd03
```

**Comment by Ernst79** [comment]
Oh, you mean in your secrets file... yes, I can add something on the conversion instruction page.

**Comment by Ernst79** [comment]
Will merge tomorrowmorning after I add something about secrets. After that, I will release a beta, to test for a few days. Unfortunately, it is not easy to make it clear in HAC that there are breaking changes.

**Review by Magalex2x14 — APPROVED** [review]

**Comment by Ernst79** [comment]
This PR is included in #150. closing this one.

**Pull request closed without merging**
