### PR TITLE
Fix for Govee H5051

### PR DESCRIPTION
**Pull request by Thrilleratplay**
I believe this will fix the issue in #467 but am unable to test as I do not own one.  There is another change that adds mapping from one device model name to another to prevent breaking the component for existing users when splitting H5051 and H5074.  This is not the most elegant solution but am open to ideas.

### CODE REVIEW

**Comment by Ernst79** [comment]
Changing device names is a bit problematic yes, I have never found a way to change the device name in the registry. Perhaps this is fine for now, but I guess the best solution should be renaming the device name in the device info. But I’m not sure that is even possible.

**Review by Ernst79 — APPROVED** [review]

**Comment by Ernst79** [comment]
I’ll merge it for now and will release a beta. Maybe later, if I ever find how to update the device info, we can modify this.

**Comment by Thrilleratplay** [comment]
@Ernst79 I did a diff of `core.device_registry` before and after, the new device names to appear to be saved/updated but could not find in `sensor.py` where this occurs.  While this is a bit of a hack, it does seem to actually update the device's model property.

**Comment by Ernst79** [comment]
Ok, that’s great. Can’t test it myself at the moment, enjoying summer holidays.

**Pull request merged**
