### PR TITLE
Component reengineering

### PR DESCRIPTION
**Pull request by Magalex2x14**
The main goal is the possibility of an individual (per device) settings for calculating states and updating the switching sensors in real-time.

ToDo:
- [x] solve #61 by fixing and bundling aioblescan with our component
- [x] mccgq02hl #115 
- [x] reworking entity classes, transferring the state calculation procedure to the entity update method
- [x] ~~split the message parser into a filter and a parser, move the logic for controlling message duplicates to the earliest possible stage~~
^postponed, because this way I lose the ability to see the number of HCI events actually processed
- [x] perform parser and accumulation of measurements in real-time as new messages arrive

### CODE REVIEW

**Comment by Magalex2x14** [comment]
Yes, it turned out to be easier to start over )

**Comment by Magalex2x14** [comment]
@Ernst79 just to keep you informed - I made the decision to force #61 (there are too many problems with this, and the further it gets, the worse it gets). While I'm doing this, 0.8.1 can be released, after which we will roll out a new beta with a fix for "NUCs" and initial support for mccgq02hl. While the owners of mccgq02hl will try the beta, I will deal with the issue of updating the binary sensors in real-time.

Alternatively, we can continue to publish intermediate beta versions step by step, and make a full-fledged release after all the described changes.

**Comment by Magalex2x14** [comment]
@Ernst79 while I was expanding the sensor classes for MCCGQ02HL, I noticed a nuance that could potentially be a problem - we have non-unique unique_id's:

```python
self._sensor_name = sensor_name(config, mac, "conductivity")
self._unique_id = "c_" + self._sensor_name
```

And here is an entry from the HA entity registry:
```
{
                "entity_id": "sensor.ble_conductivity_flower",
                "config_entry_id": null,
                "device_id": null,
                "unique_id": "c_flower",
                "platform": "ble_monitor",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 0,
                "device_class": null,
                "unit_of_measurement": "\u00b5S/cm",
                "original_name": "ble conductivity flower",
                "original_icon": "mdi:flash-circle"
},
```

I remember that earlier there was a mac address and an entity type.
As far as I understand, the mac address disappeared from the ID when the entity naming system was changed.
Did you remove the mac address for some reason?

**Comment by Ernst79** [comment]
No, it had not a specific reason to remove it. I think we should move it back to the mac address, you're right. I'll change that in the integration level branch and propose to do both one more test and release it today.

**Comment by Magalex2x14** [comment]
Wait. On the other hand, this approach gives some control over the uniqueness of the sensor name. Have you tried giving the same sensor names? Do you know, how does HA react to non-unique IDs?

**Comment by Ernst79** [comment]
I'll try, give me a few minutes.

**Comment by Ernst79** [comment]
You will get an error in the log

`Platform ble_monitor does not generate unique IDs. ID t_garden already exists - ignoring sensor.ble_temperature_garden
Home Assistant has started!`

It is only updating one of the sensors. Makes sense. I propope to change it back to `"c_" + mac`

**Comment by Magalex2x14** [comment]
I am simply confused by the fact that if we change the ID again, then those who have already updated for the beta will have to deal with the new entities again... If there is no urgent need, then maybe we can leave it as it is? :)

**Comment by Ernst79** [comment]
That's true. Users will be warned anyways. 

I now remember that I have done this to force home assistant to recreate a new sensor, as it would otherwise keep the old name with the mac at the end. The sensor name with mac at the end coupled to the unique ID when initially created without the  `name` option. When you add a `name` option, it will stick to the old name, as it is stored somewhere in the HA entity registry.

**Comment by Ernst79** [comment]
Shall we release 0.8.1 as final now?

**Comment by Magalex2x14** [comment]
I think yes, we can do it.

**Comment by Ernst79** [comment]
Ok, I'll make the merge, remove the word beta and make a release. Will you make an announcement on the forum?

**Comment by Ernst79** [comment]
Done

I'll check the beta 0.8.2 release tonight.

**Comment by Magalex2x14** [comment]
OK, thank you. In fact, I think it is better to test this branch. It works for me.
I will interrupt for now, I will continue either tonight or tomorrow ...

**Comment by Ernst79** [comment]
Ok, will do

**Comment by Ernst79** [comment]
I saw in the door sensor issue that you were looking for a possibility to restore the state on startup. This should be possible with the RestoreEntity option, see this [forum topic](https://community.home-assistant.io/t/main-purpose-of-restoreentity/135270/2). See also this [explanation](https://aarongodfrey.dev/programming/restoring-an-entity-in-home-assistant/). 

You will need to add `from homeassistant.helpers.restore_state import RestoreEntity` at the top of sensor.py and I think you will have to change `MeasuringSensor(Entity)` to `MeasuringSensor(RestoreEntity)` as well, I think.  With the `async_get_last_state()` method you should be able to restore the state.

**Comment by Magalex2x14** [comment]
Hmmm... Thank you. I think this is worth implementing, but not now. Our conversations on that issue are not very relevant, they confused me. The sensor sends data at least once a minute (judging by the dumps), as it should according to the protocol. I'll finish realtime, and then we'll see what he really had there.

**Comment by Magalex2x14** [comment]
Remained a little, looks like )

**Comment by Ernst79** [comment]
Sure, this can be implemented later. I can also have a look at it later, but for now, I let you do your work 👍

**Comment by Magalex2x14** [comment]
Wheoou... 😅
It seems to be working fine. We need to test. Please try this branch, when you have time...

**Comment by Magalex2x14** [comment]
In the morning, when I get up, I'll see what's on the forum.

**Comment by Ernst79** [comment]
Component is running fine. Strange thing is that the review option is now showing differences compared to 0.7.x, so it is impossible to see what you have changed. But I will have a look anyway.

**Comment by Magalex2x14** [comment]
> I propose that we make a new PR, based on the current master and submit your changes in there again.
OK. I will do.

**Pull request closed without merging**
