### PR TITLE
Integration level

### LINKED ISSUE #146: Move to integration domain key
According to [this ADR 0007](https://github.com/home-assistant/architecture/blob/413e3cb248cf8dca766c0280997f3b516e23fb6d/adr/0007-integration-config-yaml-structure.md), we should move mitemp_bt to the integration domain key. 

> New integrations have to put the integration configuration section under the integration domain key if configuration YAML is used.

If I understand it correctly, we should move to the following. 

```
# Allowed
mitemp_bt:
  rounding: True
  etc.

# Not allowed
sensor:
  - platform: mitemp_bt
    rounding: True
    etc.
```

It's not a big deal if we don't do this, but if we want to follow the guidelines, I think we should change this some day.

### PR DESCRIPTION
**Pull request by Ernst79**
This PR 
- changes the name of the component from `mitemp_bt` to `ble_monitor` (breaking change)
- changes the sensor platform to a integration (breaking change)
- includes the changes of beta 0.8.0 (see #142) (breaking change)

Fixes #146 and #141

### CODE REVIEW

**Review by Magalex2x14 — APPROVED** [review]
Все выглядит хорошо.

**Comment by Magalex2x14** [comment]
Lets make a beta release?

**Comment by Ernst79** [comment]
Shall we first change the repo name?

**Comment by Magalex2x14** [comment]
So I think too ... If we do this now, the current version will stop working (links will break).
But what happens if we roll out the beta without renaming the repository?

**Comment by Magalex2x14** [comment]
Hmm. Look at this: https://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github/16602311#16602311

**Comment by Magalex2x14** [comment]
It turns out that we can safely rename, github will automatically redirect to a new name.

**Comment by Magalex2x14** [comment]
Let's rename it 🤞🙈

**Comment by Ernst79** [comment]
Ok, I will do it right now. fingers crossed

**Comment by Ernst79** [comment]
Done!

**Comment by Magalex2x14** [comment]
It looks like everything is in order )

**Comment by Ernst79** [comment]
Yep, old links are redirected. Great, gives us some time to fix links

**Comment by Magalex2x14** [comment]
I changed "about" to "Xiaomi Mijia BLE MiBeacon monitor"
image

**Comment by Magalex2x14** [comment]
I tried to reinstall 0.8.0 beta - all OK (folder name stayed as mitemp_bt)

**Comment by Ernst79** [comment]
Ok, great. That is how it should be.

**Comment by Ernst79** [comment]
0.8.1-beta is released, lets try

**Comment by Ernst79** [comment]
image
 It's going too smooth

**Comment by Ernst79** [comment]
image

Also looking good, but these links never work in HACS

**Comment by Ernst79** [comment]
crap, it says (very shortly) "no content to download"

**Comment by Magalex2x14** [comment]
I'm fine, there is no such error.

**Comment by Ernst79** [comment]
has it removed the old mitemp_bt folder and installed it in the new folder?

**Comment by Magalex2x14** [comment]
Yes. All I did was change the configuration to ble_monitor

**Comment by Ernst79** [comment]
Nevermind, it worked on my end as well. Folder has changed as well. 

That was rather easy.

**Comment by Magalex2x14** [comment]
But a little scary :D

**Comment by Ernst79** [comment]
Yes, I agree. 

Has it created new sensors on your end? I got sensors with _2 at the end, but that happened earlier during testing.

**Comment by Magalex2x14** [comment]
Yes. I think we need to add a recommendation that it is worth setting names for each sensor, so that it will be easier to find them later.

**Comment by Ernst79** [comment]
Hmm, if that happens, we might get rid of the mi_ as well

**Comment by Magalex2x14** [comment]
Good idea, yes.

**Comment by Magalex2x14** [comment]
And move the 0.8.1 beta tag to the commit that includes this change (I've done this before)

**Comment by Ernst79** [comment]
Done, How do I move the 0.8.1-beta tag?

**Comment by Magalex2x14** [comment]
I am doing this with SourceTree app, dont know how to do it via website...

**Comment by Ernst79** [comment]
Can you do it than, with adding this note?

Note that your sensor names are most likely also renamed. Look for sensors that start for ble_ (e.g. `ble_temperature_livingroom`). We recommend to use the new [name](#name) option to easily rename and find your sensors.

**Comment by Magalex2x14** [comment]
Yes, I will.

**Comment by Magalex2x14** [comment]
Done.

**Comment by Magalex2x14** [comment]
My entity id's stays the same

image

I will try to disable the component, delete old entities, and enable the component back.

**Comment by Ernst79** [comment]
for me too, only friendly name has changed.

**Comment by Magalex2x14** [comment]
I suspect that when the integration name changes, users will have ble_ id's instead of _2

**Comment by Ernst79** [comment]
I know why. The entity ID is created based on the friendly name on intial setup. The entity ID is linked to (but not the same as) the unique_id. My update doesn't update the unique_id, however, it is updated when moving from sensor.mitemp_bt to ble_monitor. So, for other users, it will update to the new name after updating. Just not for us.

**Comment by Magalex2x14** [comment]
I agree, yes. Everything comes to order after deleting the entities.

**Comment by Ernst79** [comment]
Excellent. when do you want the final release?

**Comment by Magalex2x14** [comment]
Maybe in a couple of days? I will make an announcement on the forum a little later today.

**Comment by Ernst79** [comment]
Oh, I remember one more thing (sorry). In these two lines, there is a double `__`. Can this be changed to one `_`?

`self._unique_id = "cn__" + self._sensor_name`
`self._unique_id = "batt__" + self._sensor_name`

**Comment by Magalex2x14** [comment]
Yes, let's do. I'll move the tag again )

**Comment by Ernst79** [comment]
Done, better do it now.

**Comment by Magalex2x14** [comment]
Tag moved.

**Comment by Magalex2x14** [comment]
This branch does not need to be deleted when we merge - the links to the transition guide point to this branch.

**Comment by Ernst79** [comment]
We can also move the transition guide to the master branch and update the links. Or not?

**Comment by Magalex2x14** [comment]
Yes, let's do it! This does not break anything, and I will add a link to the master in the announcement.

**Comment by Ernst79** [comment]
Ok, will move it in a minute.

**Comment by Magalex2x14** [comment]
Look also at the announcement text. Have I forgotten something?

Hi to all!

A major component update is coming. Serious not by the number of changes, but in their essence.
We collected all the planned breaking changes, and decided to make them together to hurt our users only once :) 

First, we changed the name of the component to __ble_monitor__ (the repository name and the folder name with our component will change accordingly). This had to be done since the old name no longer reflects the essence of the component, and the new name gives us the freedom to implement support for other protocols (in addition to Xiaomi Mijia BLE MiBeacon) and expand the functionality of the component beyond receiving readings from sensors.

The prefix of the sensor entity names will be changed accordingly: from **`mi`** to **`ble`**.

The configuration of the component has been moved from the sensor platform level to the integration level - this also gives us more freedom in the further development of the component's functionality.

The structure of the configuration itself has also changed - the settings are grouped into the "per device" order.

The process of applying changes started today by renaming the repository and publishing version [0.8.1-beta](https://github.com/custom-components/ble_monitor/releases/tag/0.8.1-beta). Let's test its several days, and we will make a full release.

@Ernst prepared a great [guide for configuration updating](https://github.com/custom-components/ble_monitor/blob/integration_level/update_instructions.md). Please read it carefully before updating!
We strongly recommend that you register custom names for each of your sensors before updating (with the `name` option) - it will be much easier to find new entities of your sensors after updating. Do not forget to also delete old entities after updating.

We hope this transition goes smoothly for you, and we will be happy to answer any questions you may have...

**Comment by Ernst79** [comment]
Excellent.

**Review by Magalex2x14 — APPROVED** [review]

**Comment by Magalex2x14** [comment]
Everything seems to be ready? )

**Comment by Ernst79** [comment]
Yes, I think it is ready now. Thanks

**Comment by Magalex2x14** [comment]
And thank you ) Let's see how it goes )

**Pull request merged**
